### PR TITLE
heroku didn't like that bcrypt-script wasn't in Gemfile.lock

### PR DESCRIPTION
**Pull request by chrisnicholls**
Resolve the issue Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES bcrypt-ruby

### CODE REVIEW

**Comment by bmmiller** [comment]
Hmm, I specifically remember getting an warning stating not to include bcrypt **and** bcrypt-ruby anymore.  Next time I push a change to my own stuff, I can see if this is necessary, but I didn't need it before so that's weird you had an issue with it.

**Comment by chrisnicholls** [comment]
yeah it was really weird.. it error'd out when i didn't have it and then when I had it in it said this:
remote:        Post-install message from bcrypt-ruby:
remote:        #######################################################
remote:        The bcrypt-ruby gem has changed its name to just bcrypt.  Instead of
remote:        installing `bcrypt-ruby`, you should install `bcrypt`.  Please update your
remote:        dependencies accordingly.
remote:        #######################################################

So I don't know what's up with it

**Comment by bmmiller** [comment]
This PR is going to get cluttered if you continue to add other stuff to it.  The trick is usually to create another branch for the PR and then continue pushing your own modifications exclusive to you to the original master.

**Comment by chrisnicholls** [comment]
Yeah I dunno what I was thinking there. I'll just close this PR. I did log
an issue. I'm not sure what the correct solution is.

**Pull request closed without merging**
