### PR TITLE
Changepage with id

### PR DESCRIPTION
**Pull request by dschaadt**
If you have a dashboard with many subpages, it can be difficult to keep track of the individual page numbers. It is easier to give each <div class="gridster"> it's own id, e.g. <div class="gridster" id="myid"> and then to jump in data-view="Changepage" to the id in it's attribute data-page, e.g. <div data-view="Changepage" data-page="myid".
Therefore I added the following code in assets\javascript\cyleDashboards.coffee in line 322:
if !isFinite(boardnumber)
            boardnumber = $dashboards.index(document.getElementById(boardnumber)) + 1
If you use a number, it will work as before, if you use a non-numeric id it will jump to the page with the given id.

### CODE REVIEW

**Comment by bmmiller** [comment]
It seems there is quite a bit of commits and file changes over and above your description.  Can you reorganize the pull request to only include the change you are trying to add?  That being said, I don't have the ability to do anything with the pull request anyway, just know this is an awfully noisy one.

**Comment by FlorianZ** [comment]
Sorry for the late reply. What @bmmiller said: If you can bring the pull request into a more manageable state, that would really help me a lot! Thanks.

**Comment by bmmiller** [comment]
The openhab addition looks cool, but pushing it into this pull request makes it a little cluttered.  It'd be great if you could create a seperate pull request for it.

**Comment by bmmiller** [comment]
This was never an actual PR.  This was just comments on how to do something.  Closing.

**Pull request closed without merging**
