### PR TITLE
New thermostat widget

### PR DESCRIPTION
**Pull request by rjcohn**
I wrote this thermostat widget and tested with my Ecobee thermostats. It displays the temperature and allows you to change the setpoint.

### CODE REVIEW

**Comment by FlorianZ** [comment]
Just FYI all the currently open pull requests have been delayed, because I am working on a complete rewrite to make installation and configuration much easier. I will pull the new features in, once I have a better understanding of how the request will integrate with the new architecture.

**Comment by TrevorHinesley** [comment]
@FlorianZ I'm just curious as to how far the rewrite is? I'm about to set up this dashboard tomorrow, but may wait if it's close.

**Comment by bmmiller** [comment]
Hello @rjcohn, I know it's been quite a while since you submitted this but your code looks sound and we're going to bring it in, but any thoughts on adding support for "Auto" modes with two setpoints?

**Comment by rjcohn** [comment]
Good to here you're bringing it in. To be honest, I haven't done any work on this since I made the pull request. It would take me too long to come back up to speed. Sorry.

**Pull request closed without merging**
